///////////////////////////////////////////////////////////////////////////////
// GameSpy ATLAS Competition System Source File
// Copyright (c) IGN Entertainment, Inc.  All rights reserved.  
// This software is made available only pursuant to certain license terms offered
// by IGN or its subsidiary GameSpy Industries, Inc.  Unlicensed use or use in a 
// manner not expressly authorized by IGN or GameSpy is prohibited.
//
// NOTE: This is an auto-generated file, do not edit this file directly.
///////////////////////////////////////////////////////////////////////////////

#include "atlas_atlas_samples_v1.h"


const char * ATLAS_KEY_NAMES[] = 
{
	"",
	"RACE_TIME",
	"USED_VEHICLE_1",
	"USED_VEHICLE_2",
	"USED_VEHICLE_3",
	"USED_TRACK_1",
	"USED_TRACK_2",
	"USED_TRACK_3"
};

///////////////////////////////////////////////////////////////////////////////

const char * ATLAS_STAT_NAMES[] = 
{
	"",
	"NUM_CAREER_RACES",
	"NUM_CAREER_WINS",
	"NUM_CAREER_LOSSES",
	"WIN_LOSS_RATIO",
	"CURRENT_WIN_STREAK",
	"CURRENT_LOSS_STREAK",
	"LONGEST_WIN_STREAK",
	"LONGEST_LOSS_STREAK",
	"TOTAL_TIME_PLAYED",
	"BEST_RACE_TIME",
	"RANK",
	"NUM_CAREER_RACES",
	"NUM_CAREER_WINS",
	"NUM_CAREER_LOSSES",
	"WIN_LOSS_RATIO",
	"CURRENT_WIN_STREAK",
	"CURRENT_LOSS_STREAK",
	"LONGEST_WIN_STREAK",
	"LONGEST_LOSS_STREAK",
	"TOTAL_TIME_PLAYED",
	"BEST_RACE_TIME",
	"RANK",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED_TEAM",
	"NUM_TIMES_USED",
	"BEST_RACE_TIME",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED_TEAM",
	"NUM_TIMES_USED",
	"BEST_RACE_TIME",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED_TEAM",
	"NUM_TIMES_USED",
	"BEST_RACE_TIME",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED_TEAM",
	"NUM_TIMES_USED",
	"BEST_RACE_TIME",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED_TEAM",
	"NUM_TIMES_USED",
	"BEST_RACE_TIME",
	"NUM_TIMES_USED_PLAYER",
	"NUM_TIMES_USED_TEAM",
	"NUM_TIMES_USED",
	"BEST_RACE_TIME",
	"TOTAL_NUM_RACES",
	"TOTAL_TIME_PLAYED"
};

///////////////////////////////////////////////////////////////////////////////

// STAT ID to CATEGORY NAME MAP

const char * ATLAS_STAT_CATEGORY_NAMES[] = 
{
	"",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Player",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"STATS_Team",
	"METRICS_Vehicle_1",
	"METRICS_Vehicle_1",
	"METRICS_Vehicle_1",
	"METRICS_Vehicle_1",
	"METRICS_Vehicle_2",
	"METRICS_Vehicle_2",
	"METRICS_Vehicle_2",
	"METRICS_Vehicle_2",
	"METRICS_Vehicle_3",
	"METRICS_Vehicle_3",
	"METRICS_Vehicle_3",
	"METRICS_Vehicle_3",
	"METRICS_Track_1",
	"METRICS_Track_1",
	"METRICS_Track_1",
	"METRICS_Track_1",
	"METRICS_Track_2",
	"METRICS_Track_2",
	"METRICS_Track_2",
	"METRICS_Track_2",
	"METRICS_Track_3",
	"METRICS_Track_3",
	"METRICS_Track_3",
	"METRICS_Track_3",
	"METRICS_Global",
	"METRICS_Global"
};

///////////////////////////////////////////////////////////////////////////////


