/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/
#pragma once

#if !PLATFORM_IS_DEDI
#include "Pointers/1.10/HaloCE_110_Runtime.OpenSauce.inl"
#include "Pointers/1.10/HaloCE_110_Runtime_Manual.OpenSauce.inl"
#else
#include "Pointers/1.10/HaloCE_110_Dedi.OpenSauce.inl"
#endif

#include <Memory/MemoryInterface.hpp>
#include <yelolib/memory/memory_interface_base.hpp>

namespace Yelo
{
	namespace Memory
	{
		FUNC_PTR(RENDER_SKY, K_RENDER_SKY, FUNC_PTR_NULL);
		FUNC_PTR(RENDER_WINDOW_CALL_HOOK_RENDER_SKY, K_RENDER_WINDOW_CALL_HOOK_RENDER_SKY, FUNC_PTR_NULL);

		FUNC_PTR(RENDER_OBJECTS, K_RENDER_OBJECTS, FUNC_PTR_NULL);
		FUNC_PTR(RENDER_WINDOW_CALL_HOOK_RENDER_OBJECTS, K_RENDER_WINDOW_CALL_HOOK_RENDER_OBJECTS, FUNC_PTR_NULL);

		FUNC_PTR(STRUCTURE_RENDER_LIGHTMAPS, K_STRUCTURE_RENDER_LIGHTMAPS, FUNC_PTR_NULL);
		FUNC_PTR(RENDER_WINDOW_CALL_HOOK_STRUCTURE_RENDER_LIGHTMAPS, K_RENDER_WINDOW_CALL_HOOK_STRUCTURE_RENDER_LIGHTMAPS, FUNC_PTR_NULL);

		FUNC_PTR(WEATHER_PARTICLE_SYSTEMS_RENDER, K_WEATHER_PARTICLE_SYSTEMS_RENDER, FUNC_PTR_NULL);
		FUNC_PTR(RENDER_WINDOW_CALL_HOOK_WEATHER_PARTICLE_SYSTEMS_RENDER, K_RENDER_WINDOW_CALL_HOOK_WEATHER_PARTICLE_SYSTEMS_RENDER, FUNC_PTR_NULL);

		FUNC_PTR(RENDER_UI_WIDGETS, K_RENDER_UI_WIDGETS, FUNC_PTR_NULL);
		FUNC_PTR(RENDER_WINDOW_CALL_HOOK_RENDER_UI_WIDGETS, K_RENDER_WINDOW_CALL_HOOK_RENDER_UI_WIDGETS, FUNC_PTR_NULL);

		FUNC_PTR(RENDER_UI_CURSOR, K_RENDER_UI_CURSOR, FUNC_PTR_NULL);
		FUNC_PTR(CALL_HOOK_RENDER_UI_CURSOR, K_CALL_HOOK_RENDER_UI_CURSOR, FUNC_PTR_NULL);

		FUNC_PTR(INTERFACE_DRAW_SCREEN, K_INTERFACE_DRAW_SCREEN, FUNC_PTR_NULL);
		FUNC_PTR(RENDER_WINDOW_CALL_HOOK_INTERFACE_DRAW_SCREEN, K_RENDER_WINDOW_CALL_HOOK_INTERFACE_DRAW_SCREEN, FUNC_PTR_NULL);

		FUNC_PTR(UPDATE_UI_WIDGETS, K_UPDATE_UI_WIDGETS, FUNC_PTR_NULL);
		FUNC_PTR(CALL_HOOK_UPDATE_UI_WIDGETS, K_CALL_HOOK_UPDATE_UI_WIDGETS, FUNC_PTR_NULL);
	}
}
