# GameSpy Presence & Messaging SDK Makefile
# Copyright 2004 GameSpy Industries

TARGET=gptestc
THREADS=yes
DEBUG=no
CFLAGS=-W -D_NO_NOPORT_H_

SRC = \
	../../../md5c.c\
	../../../darray.c\
	../../../hashtable.c\
	../../../common/gsAssert.c\
	../../../common/gsDebug.c\
	../../../common/gsAvailable.c\
	../../../common/gsStringUtil.c\
	../../../common/gsPlatform.c\
	../../../common/gsPlatformSocket.c\
	../../../common/gsPlatformThread.c\
	../../../common/gsPlatformUtil.c\
	../../../common/gsMemory.c\
	../../../common/gsUdpEngine.c\
	../../../common/linux/LinuxCommon.c\
	../../gp.c\
	../../gpi.c\
	../../gpiBuddy.c\
	../../gpiBuffer.c\
	../../gpiCallback.c\
	../../gpiConnect.c\
	../../gpiInfo.c\
	../../gpiKeys.c\
	../../gpiOperation.c\
	../../gpiPeer.c\
	../../gpiProfile.c\
	../../gpiSearch.c\
	../../gpiUnique.c\
	../../gpiUtility.c\
	../../gpiTransfer.c\
	../gptestc.c\
	../../../gt2/gt2Auth.c\
	../../../gt2/gt2Buffer.c\
	../../../gt2/gt2Callback.c\
	../../../gt2/gt2Connection.c\
	../../../gt2/gt2Encode.c\
	../../../gt2/gt2Filter.c\
	../../../gt2/gt2Main.c\
	../../../gt2/gt2Message.c\
	../../../gt2/gt2Socket.c\
	../../../gt2/gt2Utility.c

include ../../../common/linux/Makefile.common
