# HTTP SDK Makefile
# Copyright 2004 GameSpy Industries

TARGET=ghttplinux
THREADS=yes
DEBUG=no
CFLAGS=

SRC = \
	../../../md5c.c\
	../../../darray.c\
	../../../hashtable.c\
	../../../common/linux/LinuxCommon.c\
	../../../common/gsAssert.c\
	../../../common/gsAvailable.c\
	../../../common/gsDebug.c\
	../../../common/gsCrypt.c\
	../../../common/gsLargeInt.c\
	../../../common/gsStringUtil.c\
	../../../common/gsPlatform.c\
	../../../common/gsPlatformSocket.c\
	../../../common/gsPlatformThread.c\
	../../../common/gsPlatformUtil.c\
	../../../common/gsMemory.c\
	../../../common/gsXML.c\
	../../../common/gsSHA1.c\
	../../../common/gsRC4.c\
	../../../common/gsSSL.c\
	../../ghttpBuffer.c\
	../../ghttpCallbacks.c\
	../../ghttpConnection.c\
	../../ghttpEncryption.c\
	../../ghttpMain.c\
	../../ghttpProcess.c\
	../../ghttpCommon.c\
	../../ghttpPost.c\
	../ghttpc.c

include ../../../common/linux/Makefile.common
