/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/

#if !PLATFORM_IS_DEDI
#include "Memory/1.10/Pointers/HaloCE_110_Runtime.Rasterizer.DX9.inl"
#include "Memory/1.10/Pointers/HaloCE_110_Runtime_Manual.Rasterizer.DX9.inl"
#endif

//////////////////////////////////////////////////////////////////////////
// DX9.cpp
#if __EL_INCLUDE_FILE_ID == __EL_RASTERIZER_DX9_DX9
	ENGINE_PTR(D3DPRESENT_PARAMETERS, Params,				K_PARAMS, PTR_NULL);
	ENGINE_PTR(D3DCAPS9, Caps,								K_CAPS, PTR_NULL);
	ENGINE_DPTR(IDirect3D9, D3D,							K_D3D, PTR_NULL);
	ENGINE_DPTR(IDirect3DDevice9, Device,					K_DEVICE, PTR_NULL);
	ENGINE_DPTR(IDirectInput8, DInput8,						K_DINPUT8, PTR_NULL);
	ENGINE_DPTR(IDirectInputDevice8, DInput8DeviceKeyboard,	K_DINPUT8DEVICEKEYBOARD, PTR_NULL);
	ENGINE_DPTR(IDirectInputDevice8, DInput8DeviceMouse,	K_DINPUT8DEVICEMOUSE, PTR_NULL);
	ENGINE_DPTR(IDirectInputDevice8, DInput8DeviceJoysticks,K_DINPUT8DEVICEJOYSTICKS, PTR_NULL);


//////////////////////////////////////////////////////////////////////////
// GBuffer.cpp
#elif __EL_INCLUDE_FILE_ID == __EL_RASTERIZER_DX9_GBUFFER
	ENGINE_PTR(DX9::s_vsf_entry*, VSF_TABLE_START_REFERENCE,	K_VSF_TABLE_START_REFERENCE, PTR_NULL);

	FUNC_PTR(RENDER_OBJECT_LIST_HOOK,			K_RENDER_OBJECT_LIST_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(RENDER_OBJECT_LIST_HOOK_RETN,		K_RENDER_OBJECT_LIST_HOOK_RETN, FUNC_PTR_NULL);

	FUNC_PTR(RENDER_OBJECT_LIST_END_HOOK,		K_RENDER_OBJECT_LIST_END_HOOK, FUNC_PTR_NULL);

	FUNC_PTR(RENDER_OBJECT_OBJECT_LOD_HOOK,		K_RENDER_OBJECT_OBJECT_LOD_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(RENDER_OBJECT_OBJECT_LOD_HOOK_RETN,K_RENDER_OBJECT_OBJECT_LOD_HOOK_RETN, FUNC_PTR_NULL);

	FUNC_PTR(FIRST_PERSON_WEAPON_DRAW_HOOK,		K_FIRST_PERSON_WEAPON_DRAW_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(FIRST_PERSON_WEAPON_DRAW_HOOK_RETN,K_FIRST_PERSON_WEAPON_DRAW_HOOK_RETN, FUNC_PTR_NULL);

	FUNC_PTR(COMMAND_CAMERA_SET_HOOK,			K_COMMAND_CAMERA_SET_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(COMMAND_CAMERA_SET_HOOK_RETN,		K_COMMAND_CAMERA_SET_HOOK_RETN, FUNC_PTR_NULL);

	FUNC_PTR(COMMAND_SWITCH_BSP_HOOK,			K_COMMAND_SWITCH_BSP_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(COMMAND_SWITCH_BSP_HOOK_RETN,		K_COMMAND_SWITCH_BSP_HOOK_RETN, FUNC_PTR_NULL);

	FUNC_PTR(COMMAND_GAME_SAVE_HOOK,			K_COMMAND_GAME_SAVE_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(COMMAND_GAME_SAVE_HOOK_RETN,		K_COMMAND_GAME_SAVE_HOOK_RETN, FUNC_PTR_NULL);

	FUNC_PTR(RENDER_OBJECTS_TRANSPARENT,								K_RENDER_OBJECTS_TRANSPARENT, FUNC_PTR_NULL);
	FUNC_PTR(RENDER_WINDOW_CALL_RENDER_OBJECTS_TRANSPARENT_HOOK,		K_RENDER_WINDOW_CALL_RENDER_OBJECTS_TRANSPARENT_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(RENDER_WINDOW_CALL_RENDER_OBJECTS_TRANSPARENT_RETN,		K_RENDER_WINDOW_CALL_RENDER_OBJECTS_TRANSPARENT_RETN, FUNC_PTR_NULL);

	FUNC_PTR(RASTERIZER_DRAW_STATIC_TRIANGLES_STATIC_VERTICES__DRAW_INDEXED_PRIMITIVE_HOOK, K_RASTERIZER_DRAW_STATIC_TRIANGLES_STATIC_VERTICES__DRAW_INDEXED_PRIMITIVE_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(RASTERIZER_DRAW_DYNAMIC_TRIANGLES_STATIC_VERTICES2__DRAW_INDEXED_PRIMITIVE_HOOK, K_RASTERIZER_DRAW_DYNAMIC_TRIANGLES_STATIC_VERTICES2__DRAW_INDEXED_PRIMITIVE_HOOK, FUNC_PTR_NULL);

//////////////////////////////////////////////////////////////////////////
// DX9/rasterizer_dx9_shaders_vshader9.cpp
#elif __EL_INCLUDE_FILE_ID == __EL_RASTERIZER_DX9_VSHADERS
	ENGINE_PTR(s_rasterizer_dx9_effect_collection, rasterizer_dx9_effect_collection,	K_RASTERIZER_DX9_EFFECT_COLLECTION, PTR_NULL);
	ENGINE_PTR(s_effect_shader_entry, rasterizer_effect_shaders,						K_RASTERIZER_EFFECT_SHADERS, PTR_NULL);
	ENGINE_PTR(s_vsf_entry, vsf_table,													K_VSF_TABLE, PTR_NULL);

//////////////////////////////////////////////////////////////////////////
// DeviceHooks.cpp
#elif __EL_INCLUDE_FILE_ID == __EL_RASTERIZER_DX9_DEVICEHOOKS
	FUNC_PTR(RASTERIZER_D3D_CREATE_DEVICE_HOOK,											K_RASTERIZER_D3D_CREATE_DEVICE_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(RASTERIZER_D3D_CREATE_DEVICE_RETN,											K_RASTERIZER_D3D_CREATE_DEVICE_RETN, FUNC_PTR_NULL);
	FUNC_PTR(RASTERIZER_D3D_RESET_DEVICE_HOOK,											K_RASTERIZER_D3D_RESET_DEVICE_HOOK, FUNC_PTR_NULL);
	FUNC_PTR(RASTERIZER_D3D_BEGIN_SCENE_CALL,											K_RASTERIZER_D3D_BEGIN_SCENE_CALL, FUNC_PTR_NULL);
	FUNC_PTR(RASTERIZER_D3D_END_SCENE_CALL,												K_RASTERIZER_D3D_END_SCENE_CALL, FUNC_PTR_NULL);

	FUNC_PTR(RASTERIZER_SET_WORLD_VIEW_PROJECTION_MATRIX_VERTEX_CONSTANT_CALL,			K_RASTERIZER_SET_WORLD_VIEW_PROJECTION_MATRIX_VERTEX_CONSTANT_CALL, FUNC_PTR_NULL);
	FUNC_PTR(RASTERIZER_SET_MODEL_TEX_SCALE_VERTEX_CONSTANT_CALL,						K_RASTERIZER_SET_MODEL_TEX_SCALE_VERTEX_CONSTANT_CALL, FUNC_PTR_NULL);

	static void** K_RASTERIZER_SET_MODEL_SPEC_COLOR_VERTEX_CONSTANT_CALLS[] = {
		CAST_PTR(void**, K_RASTERIZER_SET_MODEL_SPEC_COLOR_VERTEX_CONSTANT_CALL_0),
		CAST_PTR(void**, K_RASTERIZER_SET_MODEL_SPEC_COLOR_VERTEX_CONSTANT_CALL_1),
	};
	FUNC_PTR(RASTERIZER_SET_MODEL_VERTEX_LIGHT_VERTEX_CONSTANT_CALL,					K_RASTERIZER_SET_MODEL_VERTEX_LIGHT_VERTEX_CONSTANT_CALL, FUNC_PTR_NULL);
#else
	#error Undefined engine layout include for: __EL_INCLUDE_RASTERIZER_DX9
#endif