/*
	Yelo: Open Sauce SDK
		Halo 1 (CE) Edition

	See license\OpenSauce\Halo1_CE for specific license information
*/
#pragma once

#if !PLATFORM_IS_DEDI
#include "Memory/1.10/Pointers/HaloCE_110_Runtime.Rasterizer.inl"
#include "Memory/1.10/Pointers/HaloCE_110_Runtime_Manual.Rasterizer.inl"
#endif

#include <YeloLib/memory/memory_interface_base.hpp>
#include "Memory/MemoryInterface.hpp"

namespace Yelo
{
	namespace Render
	{
		namespace Sky
		{
			FUNC_PTR(FOG_ATMOSPHERIC_SKY_TAG_INDEX_HOOK, K_FOG_ATMOSPHERIC_SKY_TAG_INDEX_HOOK, FUNC_PTR_NULL);
			FUNC_PTR(FOG_ATMOSPHERIC_SKY_TAG_INDEX_RETN, K_FOG_ATMOSPHERIC_SKY_TAG_INDEX_RETN, FUNC_PTR_NULL);
			FUNC_PTR(FOG_PLANAR_SKY_TAG_INDEX_HOOK, K_FOG_PLANAR_SKY_TAG_INDEX_HOOK, FUNC_PTR_NULL);
			FUNC_PTR(FOG_PLANAR_SKY_TAG_INDEX_RETN, K_FOG_PLANAR_SKY_TAG_INDEX_RETN, FUNC_PTR_NULL);
			FUNC_PTR(RENDER_SKY_SKY_TAG_INDEX_HOOK, K_RENDER_SKY_SKY_TAG_INDEX_HOOK, FUNC_PTR_NULL);
			FUNC_PTR(RENDER_SKY_SKY_TAG_INDEX_RETN, K_RENDER_SKY_SKY_TAG_INDEX_RETN, FUNC_PTR_NULL);
			FUNC_PTR(VISIBLE_SKY_ENABLE_SKY_TAG_INDEX_HOOK, K_VISIBLE_SKY_ENABLE_SKY_TAG_INDEX_HOOK, FUNC_PTR_NULL);
			FUNC_PTR(VISIBLE_SKY_ENABLE_SKY_TAG_INDEX_RETN, K_VISIBLE_SKY_ENABLE_SKY_TAG_INDEX_RETN, FUNC_PTR_NULL);
		};
	};
}
